export const mockCourses = [
  {
    id: 1,
    title: "Lập trình Python từ Zero đến Hero",
    instructor: "Nguyễn Văn A",
    price: 599000,
    originalPrice: 999000,
    rating: 5,
    students: 2341,
    duration: "40 giờ",
    level: "Beginner",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=300&fit=crop",
    shortDescription:
      "Bắt đầu hành trình học Python từ số 0 với nội dung dễ hiểu và thực tiễn.",
    tags: ["Python", "Backend", "Web Development"],
    keywords: [
      "python",
      "backend",
      "web development",
      "lập trình",
      "lap trinh",
      "code",
      "dữ liệu",
      "du lieu",
      "cơ bản",
      "co ban",
      "flask",
      "zero",
      "hero",
    ],
    isPopular: true,
    aiScore: 95,
    userReviews: [
      {
        name: "Trần Hùng",
        comment: "Khóa học rất dễ hiểu, giảng viên giảng hay.",
        rating: 5,
      },
      {
        name: "Lê Mai",
        comment: "Phần hướng đối tượng rất bổ ích.",
        rating: 5,
      },
    ],
  },
  {
    id: 2,
    title: "Marketing Digital cho Doanh nghiệp",
    instructor: "Trần Thị B",
    price: 899000,
    originalPrice: 1299000,
    rating: 4.5,
    students: 1876,
    duration: "35 giờ",
    level: "Intermediate",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    shortDescription:
      "Học cách xây dựng chiến lược marketing hiệu quả từ chuyên gia.",
    tags: ["Digital Marketing", "SEO", "Social Media"],
    keywords: [
      "digital marketing",
      "seo",
      "social media",
      "marketing",
      "tiếp thị số",
      "tiep thi so",
      "quảng cáo",
      "quang cao",
      "content",
      "kinh doanh online",
      "facebook",
      "google",
    ],
    isPopular: false,
    aiScore: 88,
    userReviews: [
      {
        name: "Ngô Quang",
        comment: "Tôi đã áp dụng ngay vào chiến dịch công ty.",
        rating: 5,
      },
      {
        name: "Mai Hoa",
        comment: "Thực tế và dễ hiểu, tuy nhiên hơi thiếu case study.",
        rating: 4,
      },
    ],
  },
  {
    id: 3,
    title: "Thiết kế UI/UX chuyên nghiệp",
    instructor: "Lê Minh C",
    price: 1299000,
    originalPrice: 1799000,
    rating: 4,
    students: 3245,
    duration: "60 giờ",
    level: "Advanced",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=300&fit=crop",
    shortDescription:
      "Trở thành UI/UX Designer chuyên nghiệp với lộ trình bài bản.",
    tags: ["UI/UX", "Figma", "Design Thinking"],
    keywords: [
      "ui/ux",
      "ui",
      "ux",
      "figma",
      "design thinking",
      "thiết kế",
      "thiet ke",
      "giao diện",
      "giao dien",
      "trải nghiệm người dùng",
      "trai nghiem nguoi dung",
      "designer",
      "prototype",
      "wireframe",
    ],
    isPopular: true,
    aiScore: 92,
    userReviews: [
      {
        name: "Phan Bình",
        comment: "Giúp mình nâng cấp portfolio rõ rệt.",
        rating: 4,
      },
      {
        name: "Tú Anh",
        comment: "Giảng viên hỗ trợ nhiệt tình và có kinh nghiệm.",
        rating: 4,
      },
    ],
  },
  {
    id: 4,
    title: "Đầu tư Chứng khoán thông minh",
    instructor: "Phạm Văn D",
    price: 799000,
    originalPrice: 1199000,
    rating: 4.5,
    students: 987,
    duration: "25 giờ",
    level: "Beginner",
    category: "Finance",
    image:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&h=300&fit=crop",
    shortDescription:
      "Kiến thức nền tảng để bắt đầu đầu tư chứng khoán một cách bài bản.",
    tags: ["Đầu tư", "Chứng khoán", "Tài chính cá nhân"],
    keywords: [
      "đầu tư",
      "dau tu",
      "chứng khoán",
      "chung khoan",
      "tài chính",
      "tai chinh",
      "cổ phiếu",
      "co phieu",
      "phân tích kỹ thuật",
      "phan tich ky thuat",
      "tiền",
      "tien",
      "thị trường",
      "thi truong",
    ],
    isPopular: false,
    aiScore: 85,
    userReviews: [
      {
        name: "Minh Nhật",
        comment: "Tôi bắt đầu hiểu rõ hơn về thị trường.",
        rating: 4,
      },
      { name: "Thanh Huyền", comment: "Dễ hiểu và thực tế.", rating: 5 },
    ],
  },
  {
    id: 5,
    title: "React.js & Node.js Full Stack",
    instructor: "Hoàng Thị E",
    price: 1499000,
    originalPrice: 1999000,
    rating: 4.5,
    students: 4567,
    duration: "80 giờ",
    level: "Advanced",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=300&fit=crop",
    shortDescription: "Học toàn bộ quy trình xây dựng web với React và Node.",
    tags: ["React", "Node.js", "Full Stack"],
    keywords: [
      "react",
      "reactjs",
      "node",
      "nodejs",
      "full stack",
      "fullstack",
      "lập trình web",
      "lap trinh web",
      "javascript",
      "js",
      "mongodb",
      "express",
      "frontend",
      "backend",
    ],
    isPopular: true,
    aiScore: 97,
    userReviews: [
      {
        name: "Nguyễn Long",
        comment: "Khóa học tốt nhất về full stack mình từng học.",
        rating: 5,
      },
      {
        name: "Trần Hiếu",
        comment: "Rất đầy đủ, bài tập nhiều và sát với thực tế.",
        rating: 4,
      },
    ],
  },
  {
    id: 6,
    title: "Photoshop cho người mới bắt đầu",
    instructor: "Võ Minh F",
    price: 399000,
    originalPrice: 699000,
    rating: 4,
    students: 2103,
    duration: "30 giờ",
    level: "Beginner",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1609921141835-710b7fa6e438?w=400&h=300&fit=crop",
    shortDescription: "Nắm vững kỹ năng Photoshop cơ bản chỉ trong 30 giờ.",
    tags: ["Photoshop", "Graphic Design", "Photo Editing"],
    keywords: [
      "photoshop",
      "graphic design",
      "photo editing",
      "thiết kế đồ họa",
      "thiet ke do hoa",
      "chỉnh sửa ảnh",
      "chinh sua anh",
      "pts",
      "adobe",
      "banner",
      "poster",
    ],
    isPopular: false,
    aiScore: 78,
    userReviews: [
      {
        name: "Đỗ Hạnh",
        comment: "Giúp mình thiết kế ảnh cho dự án cá nhân rất tốt.",
        rating: 4,
      },
      {
        name: "Nam Trường",
        comment: "Phần thực hành khá đầy đủ, nên có thêm video nâng cao.",
        rating: 4,
      },
    ],
  },
  {
    id: 7,
    title: "English Communication - Giao tiếp tiếng Anh cơ bản",
    instructor: "Sarah Johnson",
    price: 799000,
    originalPrice: 1099000,
    rating: 4.8,
    students: 5432,
    duration: "45 giờ",
    level: "Beginner",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop",
    shortDescription: "Học giao tiếp tiếng Anh thực tế với giáo viên bản ngữ.",
    tags: ["English", "Communication", "Speaking"],
    keywords: [
      "english",
      "communication",
      "speaking",
      "giao tiếp",
      "giao tiep",
      "tiếng anh",
      "tieng anh",
      "nghe nói",
      "nghe noi",
      "phát âm",
      "phat am",
      "bản ngữ",
      "ban ngu",
      "người mỹ",
      "nguoi my",
      "american",
      "giáo viên nước ngoài",
      "giao vien nuoc ngoai",
    ],
    isPopular: true,
    aiScore: 91,
    userReviews: [
      {
        name: "Nguyễn Linh",
        comment: "Giáo viên phát âm rất chuẩn, dễ theo dõi.",
        rating: 5,
      },
      {
        name: "Tô Minh",
        comment: "Khóa học giúp mình tự tin giao tiếp hơn.",
        rating: 5,
      },
    ],
  },
  {
    id: 8,
    title: "IELTS 7.0+ - Chinh phục kỳ thi IELTS",
    instructor: "Michael Brown",
    price: 1299000,
    originalPrice: 1699000,
    rating: 4.6,
    students: 3876,
    duration: "70 giờ",
    level: "Intermediate",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=300&fit=crop",
    shortDescription: "Lộ trình học IELTS bài bản để đạt 7.0+ từ chuyên gia.",
    tags: ["IELTS", "Test Preparation", "Academic English"],
    keywords: [
      "ielts",
      "test preparation",
      "academic english",
      "luyện thi",
      "luyen thi",
      "chứng chỉ",
      "chung chi",
      "du học",
      "du hoc",
      "writing",
      "reading",
      "listening",
      "speaking",
      "bản ngữ",
      "ban ngu",
      "american",
      "british",
    ],
    isPopular: true,
    aiScore: 94,
    userReviews: [
      {
        name: "Lê Thùy",
        comment: "Đã đạt 7.5 sau khi học khóa này!",
        rating: 5,
      },
      {
        name: "Phạm Đức",
        comment: "Phần Writing Task 2 rất hữu ích.",
        rating: 4,
      },
    ],
  },
  {
    id: 9,
    title: "Business English - Tiếng Anh thương mại",
    instructor: "Emma Wilson",
    price: 999000,
    originalPrice: 1399000,
    rating: 4.4,
    students: 2156,
    duration: "50 giờ",
    level: "Intermediate",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
    shortDescription: "Tiếng Anh chuyên ngành cho môi trường làm việc quốc tế.",
    tags: ["Business English", "Professional", "Workplace"],
    keywords: [
      "business english",
      "professional",
      "workplace",
      "tiếng anh thương mại",
      "tieng anh thuong mai",
      "công sở",
      "cong so",
      "email",
      "thuyết trình",
      "thuyet trinh",
      "đàm phán",
      "dam phan",
      "đi làm",
      "di lam",
      "bản ngữ",
      "ban ngu",
    ],
    isPopular: false,
    aiScore: 87,
    userReviews: [
      {
        name: "Trần Hải",
        comment: "Rất thực tế cho công việc hàng ngày.",
        rating: 4,
      },
      {
        name: "Ngô Lan",
        comment: "Phần email templates rất hữu ích.",
        rating: 5,
      },
    ],
  },
  {
    id: 10,
    title: "Java Spring Boot - Xây dựng REST API",
    instructor: "Nguyễn Minh Tú",
    price: 1199000,
    originalPrice: 1599000,
    rating: 4.7,
    students: 1987,
    duration: "65 giờ",
    level: "Intermediate",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=300&fit=crop",
    shortDescription: "Học Spring Boot để xây dựng REST API và microservices.",
    tags: ["Java", "Spring Boot", "REST API"],
    keywords: [
      "java",
      "spring",
      "springboot",
      "spring boot",
      "rest api",
      "api",
      "backend",
      "microservices",
      "lập trình",
      "lap trinh",
    ],
    isPopular: true,
    aiScore: 93,
    userReviews: [
      {
        name: "Vũ Hồng",
        comment: "Giải thích rất chi tiết về Spring ecosystem.",
        rating: 5,
      },
      { name: "Đặng Tuấn", comment: "Dự án cuối khóa rất thực tế.", rating: 4 },
    ],
  },
  {
    id: 11,
    title: "Flutter - Phát triển ứng dụng di động",
    instructor: "Lê Quang Vinh",
    price: 1099000,
    originalPrice: 1499000,
    rating: 4.3,
    students: 2743,
    duration: "55 giờ",
    level: "Intermediate",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
    shortDescription: "Tạo app di động đa nền tảng với Flutter và Dart.",
    tags: ["Flutter", "Mobile Development", "Cross-platform"],
    keywords: [
      "flutter",
      "mobile development",
      "cross-platform",
      "làm app",
      "lam app",
      "di động",
      "di dong",
      "ứng dụng",
      "ung dung",
      "ios",
      "android",
      "dart",
    ],
    isPopular: false,
    aiScore: 89,
    userReviews: [
      {
        name: "Bùi Thảo",
        comment: "Flutter thật sự mạnh mẽ cho mobile dev.",
        rating: 4,
      },
      {
        name: "Cao Duy",
        comment: "Cần thêm phần về state management nâng cao.",
        rating: 4,
      },
    ],
  },
  {
    id: 12,
    title: "Data Science với Python",
    instructor: "Phạm Thị Hằng",
    price: 1399000,
    originalPrice: 1899000,
    rating: 4.6,
    students: 1654,
    duration: "75 giờ",
    level: "Advanced",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
    shortDescription:
      "Trở thành Data Scientist với Python và Machine Learning.",
    tags: ["Data Science", "Python", "Machine Learning"],
    keywords: [
      "data science",
      "python",
      "machine learning",
      "khoa học dữ liệu",
      "khoa hoc du lieu",
      "phân tích dữ liệu",
      "phan tich du lieu",
      "ai",
      "pandas",
      "numpy",
      "matplotlib",
      "scikit-learn",
    ],
    isPopular: true,
    aiScore: 96,
    userReviews: [
      {
        name: "Trịnh Hoa",
        comment: "Khóa học rất thực tế với nhiều dataset thực tế.",
        rating: 5,
      },
      {
        name: "Lý Bảo",
        comment: "Phần ML algorithms được giải thích rất rõ.",
        rating: 4,
      },
    ],
  },
  {
    id: 13,
    title: "Video Editing với Adobe Premiere Pro",
    instructor: "Nguyễn Thành Đạt",
    price: 699000,
    originalPrice: 999000,
    rating: 4.2,
    students: 3421,
    duration: "40 giờ",
    level: "Beginner",
    category: "Design",
    image:
      "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&h=300&fit=crop",
    shortDescription: "Học cách edit video chuyên nghiệp với Premiere Pro.",
    tags: ["Video Editing", "Premiere Pro", "Post-production"],
    keywords: [
      "video editing",
      "premiere pro",
      "premiere",
      "post-production",
      "dựng phim",
      "dung phim",
      "làm video",
      "lam video",
      "chỉnh sửa video",
      "chinh sua video",
      "youtube",
      "tiktok",
      "adobe",
    ],
    isPopular: false,
    aiScore: 83,
    userReviews: [
      {
        name: "Hoàng Anh",
        comment: "Giúp mình edit video cho kênh YouTube.",
        rating: 4,
      },
      {
        name: "Đinh Hương",
        comment: "Phần color grading rất hữu ích.",
        rating: 4,
      },
    ],
  },
  {
    id: 14,
    title: "Accounting Basics - Kế toán cơ bản",
    instructor: "Trần Thị Loan",
    price: 599000,
    originalPrice: 899000,
    rating: 4.1,
    students: 1876,
    duration: "35 giờ",
    level: "Beginner",
    category: "Finance",
    image:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop",
    shortDescription: "Nắm vững kiến thức kế toán cơ bản cho doanh nghiệp.",
    tags: ["Accounting", "Finance", "Business"],
    keywords: [
      "accounting",
      "finance",
      "business",
      "kế toán",
      "ke toan",
      "thuế",
      "thue",
      "báo cáo tài chính",
      "bao cao tai chinh",
      "doanh nghiệp",
      "doanh nghiep",
    ],
    isPopular: false,
    aiScore: 79,
    userReviews: [
      { name: "Lê Quân", comment: "Dễ hiểu và áp dụng được ngay.", rating: 4 },
      { name: "Nguyệt Hà", comment: "Cần thêm ví dụ thực tế hơn.", rating: 4 },
    ],
  },
  {
    id: 15,
    title: "Copywriting - Viết bán hàng hiệu quả",
    instructor: "Đỗ Minh Châu",
    price: 899000,
    originalPrice: 1299000,
    rating: 4.8,
    students: 2987,
    duration: "30 giờ",
    level: "Beginner",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=300&fit=crop",
    shortDescription: "Học cách viết content thu hút và chuyển đổi khách hàng.",
    tags: ["Copywriting", "Content Marketing", "Sales"],
    keywords: [
      "copywriting",
      "content marketing",
      "sales",
      "viết lách",
      "viet lach",
      "content",
      "bán hàng",
      "ban hang",
      "quảng cáo",
      "quang cao",
      "marketing",
      "headline",
    ],
    isPopular: true,
    aiScore: 90,
    userReviews: [
      {
        name: "Phan Thảo",
        comment: "Tỷ lệ chuyển đổi của mình tăng 200% sau khóa học.",
        rating: 5,
      },
      {
        name: "Vũ Hải",
        comment: "Techniques rất thực tế và dễ áp dụng.",
        rating: 5,
      },
    ],
  },
  {
    id: 16,
    title: "Machine Learning cơ bản",
    instructor: "Nguyễn Văn Khoa",
    price: 1199000,
    originalPrice: 1699000,
    rating: 4.4,
    students: 1324,
    duration: "60 giờ",
    level: "Intermediate",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=400&h=300&fit=crop",
    shortDescription:
      "Khám phá thế giới AI và Machine Learning một cách dễ hiểu.",
    tags: ["Machine Learning", "AI", "Python"],
    keywords: [
      "machine learning",
      "ai",
      "python",
      "học máy",
      "hoc may",
      "trí tuệ nhân tạo",
      "tri tue nhan tao",
      "ml",
      "thuật toán",
      "thuat toan",
      "deep learning",
    ],
    isPopular: true,
    aiScore: 92,
    userReviews: [
      {
        name: "Huỳnh Tân",
        comment: "Giải thích thuật toán rất dễ hiểu.",
        rating: 4,
      },
      {
        name: "Phạm Nhung",
        comment: "Cần thêm phần Deep Learning.",
        rating: 4,
      },
    ],
  },
  {
    id: 17,
    title: "TOEIC 990 - Chinh phục TOEIC",
    instructor: "Jennifer Smith",
    price: 899000,
    originalPrice: 1199000,
    rating: 4.5,
    students: 4521,
    duration: "50 giờ",
    level: "Intermediate",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop",
    shortDescription: "Đạt điểm cao TOEIC với phương pháp học thông minh.",
    tags: ["TOEIC", "Test Preparation", "English"],
    keywords: [
      "toeic",
      "test preparation",
      "english",
      "luyện thi",
      "luyen thi",
      "chứng chỉ",
      "chung chi",
      "tiếng anh",
      "tieng anh",
      "đi làm",
      "di lam",
      "listening",
      "reading",
      "bản ngữ",
      "ban ngu",
    ],
    isPopular: true,
    aiScore: 88,
    userReviews: [
      {
        name: "Lê Tuấn",
        comment: "Từ 650 lên 900 điểm sau 3 tháng học.",
        rating: 5,
      },
      {
        name: "Võ Hạnh",
        comment: "Phần Listening techniques rất hay.",
        rating: 4,
      },
    ],
  },
  {
    id: 18,
    title: "WordPress - Tạo website không cần code",
    instructor: "Lê Văn Phúc",
    price: 699000,
    originalPrice: 999000,
    rating: 4.0,
    students: 3654,
    duration: "35 giờ",
    level: "Beginner",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=400&h=300&fit=crop",
    shortDescription: "Xây dựng website chuyên nghiệp với WordPress.",
    tags: ["WordPress", "Web Development", "CMS"],
    keywords: [
      "wordpress",
      "web development",
      "cms",
      "làm web",
      "lam web",
      "website",
      "blog",
      "bán hàng online",
      "ban hang online",
      "không cần code",
      "khong can code",
    ],
    isPopular: false,
    aiScore: 81,
    userReviews: [
      {
        name: "Trần Huy",
        comment: "Đã tạo được website cho shop của mình.",
        rating: 4,
      },
      { name: "Lý Ngọc", comment: "Phần SEO cần chi tiết hơn.", rating: 4 },
    ],
  },
  {
    id: 19,
    title: "Personal Finance - Quản lý tài chính cá nhân",
    instructor: "Nguyễn Thị Hương",
    price: 599000,
    originalPrice: 849000,
    rating: 4.6,
    students: 2876,
    duration: "25 giờ",
    level: "Beginner",
    category: "Finance",
    image:
      "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=400&h=300&fit=crop",
    shortDescription:
      "Học cách quản lý tiền bạc thông minh và đầu tư hiệu quả.",
    tags: ["Personal Finance", "Investment", "Budgeting"],
    keywords: [
      "personal finance",
      "investment",
      "budgeting",
      "quản lý tài chính cá nhân",
      "quan ly tai chinh ca nhan",
      "tiết kiệm",
      "tiet kiem",
      "đầu tư",
      "dau tu",
      "tiền bạc",
      "tien bac",
    ],
    isPopular: true,
    aiScore: 86,
    userReviews: [
      {
        name: "Phạm Duy",
        comment: "Giúp mình có thái độ tích cực với tiền bạc.",
        rating: 5,
      },
      { name: "Tô Lan", comment: "Rất thực tế và dễ áp dụng.", rating: 4 },
    ],
  },
  {
    id: 20,
    title: "Social Media Marketing - Chinh phục mạng xã hội",
    instructor: "Đặng Thị Mai",
    price: 799000,
    originalPrice: 1099000,
    rating: 4.7,
    students: 3245,
    duration: "42 giờ",
    level: "Intermediate",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=400&h=300&fit=crop",
    shortDescription:
      "Xây dựng thương hiệu mạnh mẽ trên các nền tảng mạng xã hội.",
    tags: ["Social Media", "Content Strategy", "Brand Building"],
    keywords: [
      "social media",
      "content strategy",
      "brand building",
      "mạng xã hội",
      "mang xa hoi",
      "facebook",
      "instagram",
      "tiktok",
      "youtube",
      "smm",
    ],
    isPopular: true,
    aiScore: 89,
    userReviews: [
      {
        name: "Nguyễn Trang",
        comment: "Follower Instagram tăng từ 1K lên 50K trong 6 tháng.",
        rating: 5,
      },
      {
        name: "Lê Hoàng",
        comment: "Strategies cho TikTok rất hiệu quả.",
        rating: 4,
      },
    ],
  },
  {
    id: 21,
    title: "iOS App Development với Swift",
    instructor: "Trần Quốc Bảo",
    price: 1299000,
    originalPrice: 1699000,
    rating: 4.3,
    students: 1567,
    duration: "70 giờ",
    level: "Advanced",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=300&fit=crop",
    shortDescription: "Phát triển ứng dụng iOS native với Swift và SwiftUI.",
    tags: ["iOS", "Swift", "Mobile Development"],
    keywords: [
      "ios",
      "swift",
      "swiftui",
      "uikit",
      "mobile development",
      "lập trình app",
      "lap trinh app",
      "iphone",
      "apple",
      "app store",
    ],
    isPopular: false,
    aiScore: 91,
    userReviews: [
      {
        name: "Phan Việt",
        comment: "SwiftUI thật sự tuyệt vời cho UI development.",
        rating: 4,
      },
      {
        name: "Ngô Thắng",
        comment: "Cần thêm phần về advanced iOS features.",
        rating: 4,
      },
    ],
  },
  {
    id: 22,
    title: "Pronunciation Perfect - Phát âm tiếng Anh chuẩn",
    instructor: "Robert Johnson",
    price: 599000,
    originalPrice: 799000,
    rating: 4.9,
    students: 6789,
    duration: "30 giờ",
    level: "Beginner",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=300&fit=crop",
    shortDescription: "Cải thiện phát âm tiếng Anh với giáo viên bản ngữ.",
    tags: ["Pronunciation", "Speaking", "Phonetics"],
    keywords: [
      "pronunciation",
      "speaking",
      "phonetics",
      "phát âm",
      "phat am",
      "nói tiếng anh",
      "noi tieng anh",
      "bản ngữ",
      "ban ngu",
      "ipa",
      "ngữ điệu",
      "ngu dieu",
      "người mỹ",
      "nguoi my",
      "american",
      "chuẩn giọng",
      "chuan giong",
    ],
    isPopular: true,
    aiScore: 95,
    userReviews: [
      {
        name: "Vũ Linh",
        comment: "Phát âm của mình cải thiện rõ rệt chỉ sau 2 tuần.",
        rating: 5,
      },
      {
        name: "Trần Bình",
        comment: "Giáo viên rất kiên nhẫn và chuyên nghiệp.",
        rating: 5,
      },
    ],
  },
  {
    id: 23,
    title: "Excel Advanced - Thành thạo Excel nâng cao",
    instructor: "Lê Thị Nga",
    price: 699000,
    originalPrice: 999000,
    rating: 4.4,
    students: 4321,
    duration: "45 giờ",
    level: "Intermediate",
    category: "Office Skill",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop",
    shortDescription:
      "Nâng cao kỹ năng Excel với các công thức và macro phức tạp.",
    tags: ["Excel", "Data Analysis", "Office Skills"],
    keywords: [
      "excel",
      "data analysis",
      "office skills",
      "tin học văn phòng",
      "tin hoc van phong",
      "hàm",
      "ham",
      "vlookup",
      "pivot table",
      "dashboard",
      "macro",
      "vba",
      "phân tích dữ liệu",
      "phan tich du lieu",
    ],
    isPopular: true,
    aiScore: 87,
    userReviews: [
      {
        name: "Nguyễn Hạnh",
        comment: "Công việc xử lý data nhanh hơn rất nhiều.",
        rating: 4,
      },
      { name: "Phạm Tuấn", comment: "Phần Dashboard rất thực tế.", rating: 5 },
    ],
  },
  {
    id: 24,
    title: "Blockchain & Cryptocurrency cơ bản",
    instructor: "Đỗ Văn Hiệp",
    price: 899000,
    originalPrice: 1199000,
    rating: 4.2,
    students: 2134,
    duration: "40 giờ",
    level: "Beginner",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=300&fit=crop",
    shortDescription:
      "Hiểu về công nghệ Blockchain và thị trường Cryptocurrency.",
    tags: ["Blockchain", "Cryptocurrency", "DeFi"],
    keywords: [
      "blockchain",
      "cryptocurrency",
      "crypto",
      "defi",
      "tiền ảo",
      "tien ao",
      "tiền mã hóa",
      "tien ma hoa",
      "bitcoin",
      "btc",
      "ethereum",
      "eth",
      "đầu tư",
      "dau tu",
    ],
    isPopular: false,
    aiScore: 84,
    userReviews: [
      {
        name: "Lý Hưng",
        comment: "Giúp mình hiểu rõ hơn về công nghệ blockchain.",
        rating: 4,
      },
      {
        name: "Trần Hoa",
        comment: "Cần cập nhật thêm về các dự án DeFi mới.",
        rating: 4,
      },
    ],
  },
  {
    id: 25,
    title: "Google Ads Mastery - Quảng cáo Google hiệu quả",
    instructor: "Vũ Minh Đức",
    price: 999000,
    originalPrice: 1399000,
    rating: 4.6,
    students: 2987,
    duration: "48 giờ",
    level: "Intermediate",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
    shortDescription: "Làm chủ Google Ads để tăng doanh số và ROI.",
    tags: ["Google Ads", "PPC", "Digital Advertising"],
    keywords: [
      "google ads",
      "adwords",
      "ppc",
      "digital advertising",
      "quảng cáo google",
      "quang cao google",
      "marketing",
      "chạy ads",
      "chay ads",
      "sem",
    ],
    isPopular: true,
    aiScore: 90,
    userReviews: [
      {
        name: "Nguyễn Quang",
        comment: "ROAS tăng từ 200% lên 500% sau khóa học.",
        rating: 5,
      },
      {
        name: "Lê Thảo",
        comment: "Quality Score của ads cải thiện đáng kể.",
        rating: 4,
      },
    ],
  },
  {
    id: 26,
    title: "Public Speaking - Thuyết trình tự tin",
    instructor: "Nguyễn Thanh Hà",
    price: 799000,
    originalPrice: 1099000,
    rating: 4.8,
    students: 3456,
    duration: "35 giờ",
    level: "Beginner",
    category: "Soft Skill",
    image:
      "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=300&fit=crop",
    shortDescription: "Vượt qua nỗi sợ và thuyết trình tự tin trước đám đông.",
    tags: ["Public Speaking", "Communication", "Confidence"],
    keywords: [
      "public speaking",
      "communication",
      "confidence",
      "thuyết trình",
      "thuyet trinh",
      "nói trước đám đông",
      "noi truoc dam dong",
      "giao tiếp",
      "giao tiep",
      "tự tin",
      "tu tin",
      "kỹ năng mềm",
      "ky nang mem",
    ],
    isPopular: true,
    aiScore: 92,
    userReviews: [
      {
        name: "Trần Hùng",
        comment: "Từ người sợ nói chuyện thành MC của công ty.",
        rating: 5,
      },
      {
        name: "Lý Tâm",
        comment: "Techniques để control nervousness rất hữu ích.",
        rating: 5,
      },
    ],
  },
  {
    id: 27,
    title: "DevOps cơ bản - Docker & Kubernetes",
    instructor: "Hoàng Văn Tài",
    price: 1199000,
    originalPrice: 1599000,
    rating: 4.5,
    students: 1876,
    duration: "55 giờ",
    level: "Intermediate",
    category: "Programming",
    image:
      "https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=400&h=300&fit=crop",
    shortDescription: "Học DevOps với Docker, Kubernetes và CI/CD pipelines.",
    tags: ["DevOps", "Docker", "Kubernetes"],
    keywords: [
      "devops",
      "docker",
      "kubernetes",
      "k8s",
      "ci/cd",
      "github",
      "hệ thống",
      "he thong",
      "deployment",
      "triển khai",
      "trien khai",
    ],
    isPopular: false,
    aiScore: 93,
    userReviews: [
      {
        name: "Nguyễn Khang",
        comment: "Deployment process nhanh hơn rất nhiều.",
        rating: 4,
      },
      {
        name: "Phạm Linh",
        comment: "Kubernetes phần hơi khó, cần thêm ví dụ.",
        rating: 4,
      },
    ],
  },
  {
    id: 28,
    title: "Conversational English - Tiếng Anh giao tiếp nâng cao",
    instructor: "Anna Thompson",
    price: 899000,
    originalPrice: 1199000,
    rating: 4.7,
    students: 4567,
    duration: "55 giờ",
    level: "Intermediate",
    category: "English",
    image:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop",
    shortDescription:
      "Nâng cao kỹ năng giao tiếp tiếng Anh trong mọi tình huống.",
    tags: ["Conversational English", "Advanced Speaking", "Fluency"],
    keywords: [
      "conversational english",
      "advanced speaking",
      "fluency",
      "giao tiếp nâng cao",
      "giao tiep nang cao",
      "nói chuyện",
      "noi chuyen",
      "thành ngữ",
      "thanh ngu",
      "idioms",
      "phrasal verbs",
      "bản ngữ",
      "ban ngu",
      "nước ngoài",
      "nuoc ngoai",
    ],
    isPopular: true,
    aiScore: 91,
    userReviews: [
      {
        name: "Vũ Hạnh",
        comment: "Confidence trong giao tiếp tăng đáng kể.",
        rating: 5,
      },
      {
        name: "Lê Dương",
        comment: "Cultural context rất bổ ích cho công việc.",
        rating: 4,
      },
    ],
  },
  {
    id: 29,
    title: "Photography cơ bản - Chụp ảnh đẹp",
    instructor: "Đặng Minh Tâm",
    price: 799000,
    originalPrice: 1099000,
    rating: 4.3,
    students: 2765,
    duration: "40 giờ",
    level: "Beginner",
    category: "Art",
    image:
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=300&fit=crop",
    shortDescription: "Học cách chụp ảnh đẹp với máy ảnh và điện thoại.",
    tags: ["Photography", "Camera", "Visual Arts"],
    keywords: [
      "photography",
      "camera",
      "visual arts",
      "nhiếp ảnh",
      "nhiep anh",
      "chụp ảnh",
      "chup anh",
      "máy ảnh",
      "may anh",
      "lightroom",
      "bố cục",
      "bo cuc",
      "chân dung",
      "chan dung",
      "phong cảnh",
      "phong canh",
    ],
    isPopular: false,
    aiScore: 85,
    userReviews: [
      {
        name: "Trần Linh",
        comment: "Ảnh chụp bằng phone cũng đẹp hơn rất nhiều.",
        rating: 4,
      },
      {
        name: "Ngô Trang",
        comment: "Composition rules rất hữu ích.",
        rating: 4,
      },
    ],
  },
  {
    id: 30,
    title: "Cybersecurity Fundamentals - Bảo mật thông tin",
    instructor: "Lê Quang Huy",
    price: 1099000,
    originalPrice: 1499000,
    rating: 4.4,
    students: 1543,
    duration: "50 giờ",
    level: "Intermediate",
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=300&fit=crop",
    shortDescription:
      "Học cách bảo vệ hệ thống và dữ liệu khỏi các mối đe dọa.",
    tags: ["Cybersecurity", "Network Security", "Ethical Hacking"],
    keywords: [
      "cybersecurity",
      "network security",
      "ethical hacking",
      "bảo mật",
      "bao mat",
      "an ninh mạng",
      "an ninh mang",
      "hacker",
      "pentest",
      "bảo mật thông tin",
      "bao mat thong tin",
    ],
    isPopular: true,
    aiScore: 88,
    userReviews: [
      {
        name: "Phạm Đức",
        comment: "Kiến thức security rất cần thiết cho developer.",
        rating: 4,
      },
      {
        name: "Trần Hải",
        comment: "Practical exercises rất bổ ích.",
        rating: 5,
      },
    ],
  },
];

export const getAllCourses = async () => {
  return new Promise((resolve) => {
    const data = [...mockCourses].sort((a, b) => b.isPopular - a.isPopular);
    setTimeout(() => {
      resolve({ data });
    }, 1000);
  });
};

export const fetchSuggestions = async (userId) => {
  fetch(`http://fake-api.com/api/suggestions?userId=${userId}`)
    .then((res) => console.log(res))
    .catch((err) => console.log(err));

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (Math.random() < 0.2) {
        reject(new Error("Không thể lấy gợi ý lúc này"));
      } else {
        const mockSuggestedProducts = mockCourses
          .filter((course) => course.aiScore > 90)
          .sort((a, b) => b.aiScore - a.aiScore)
          .slice(0, 3);
        resolve({ data: mockSuggestedProducts });
      }
    }, 3000);
  });
};
